Improve the default download path.
Currently it defaults to $CWD/Downloads and if this path doesn't exist,
we get a crash:

```
thread '<unnamed>' panicked at 'Unable to open file 'Downloads/img.jpg'', src/controller.rs:762:37
```

This confused me.

So this change makes things more user friendly by:
 a) Selecting either ~/Downloads or /tmp as the default download path.
 b) Creating the path if it doesn't exist.